--- 
before_script: 
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - "wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.42/checkstyle-8.42-all.jar -P jars/"
jdk: 
  - openjdk11
language: java
script: 
  - "mvn compile"
  - "mvn test"
  - "java -jar jars/checkstyle-8.42-all.jar -c src/test/checkstyle/google_checks.xml src/main/java/"
after_script:
  - "rm jars/checkstyle-8.42-all.jar"
